# Generated by Django 3.2 on 2023-02-25 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('date_du_vol', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('heure_du_vol', models.TimeField()),
                ('places_restantes', models.IntegerField()),
                ('prix_ticket', models.IntegerField()),
            ],
        ),
    ]
