# Generated by Django 4.1.6 on 2023-02-17 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('escale', models.CharField(max_length=150)),
                ('date_du_vol', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('heure_du_vol', models.TimeField()),
                ('places_restantes', models.IntegerField()),
                ('prix_billet', models.IntegerField()),
            ],
        ),
    ]
