# Generated by Django 3.2 on 2023-03-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='prix_ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='prix',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='depart',
            field=models.CharField(choices=[('Bunia', 'Bunia'), ('Kisangani', 'Kisangani'), ('Aru', 'Aru'), ('Mahagi', 'Bunia'), ('Beni', 'Kisangani')], default='New', max_length=150),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destination',
            field=models.CharField(choices=[('Kisangani', 'Kisangani'), ('Bunia', 'Bunia'), ('Aru', 'Aru'), ('Beni', 'Kisangani'), ('Mahagi', 'Bunia')], default='New', max_length=150),
        ),
    ]
