# Generated by Django 3.2 on 2023-03-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20230301_0512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='prix',
            new_name='prix_ticket',
        ),
    ]
