# Generated by Django 3.2 on 2023-03-01 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_rename_prix_ticket_prix_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_du_vol',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
