# Generated by Django 3.2 on 2023-03-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_date_du_vol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='depart',
            field=models.CharField(choices=[('Bunia', 'Bunia'), ('Kisangani', 'Kisangani'), ('Aru', 'Aru'), ('Mahagi', 'Mahagi'), ('Beni', 'Beni'), ('Goma', 'Goma')], default='New', max_length=150),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destination',
            field=models.CharField(choices=[('Bunia', 'Bunia'), ('Kisangani', 'Kisangani'), ('Aru', 'Aru'), ('Mahagi', 'Mahagi'), ('Beni', 'Beni'), ('Goma', 'Goma')], default='New', max_length=150),
        ),
    ]
