# Generated by Django 3.2 on 2023-03-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20230302_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_1',
            new_name='civilite',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='nom_de_famille',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_line_2',
            new_name='prenom',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('S', 'Shipping')], max_length=1),
        ),
    ]
