# Generated by Django 3.2 on 2023-03-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20230302_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='civilite',
            new_name='civilité',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='prenom',
            new_name='prénom',
        ),
    ]
