# Generated by Django 3.2 on 2023-03-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20230302_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='civilité',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mme', 'Mme'), ('Mlle', 'Mlle')], default='Mr', max_length=150),
        ),
    ]
